export const siteConfig = {
  name: "NestHelper",
  brand: "NestHelper",
  subheading: "Parent Reset",
  slogan: "Reset the home. Reclaim the day.",
  domain: "NestHelperWA.com",
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "hello@nesthelperwa.com",
  emails: {
    support: process.env.NEXT_PUBLIC_SUPPORT_EMAIL || "support@nesthelperwa.com",
    booking: process.env.NEXT_PUBLIC_BOOKING_EMAIL || "booking@nesthelperwa.com",
    requests: process.env.NEXT_PUBLIC_REQUESTS_EMAIL || "requests@nesthelperwa.com",
    billing: process.env.NEXT_PUBLIC_BILLING_EMAIL || "billing@nesthelperwa.com",
    payments: process.env.NEXT_PUBLIC_PAYMENTS_EMAIL || "payments@nesthelperwa.com",
    laundry: process.env.NEXT_PUBLIC_LAUNDRY_EMAIL || "laundry@nesthelperwa.com",
    commercial: process.env.NEXT_PUBLIC_COMMERCIAL_EMAIL || "commercial@nesthelperwa.com",
    helpers: process.env.NEXT_PUBLIC_HELPERS_EMAIL || "helpers@nesthelperwa.com",
    partners: process.env.NEXT_PUBLIC_PARTNERS_EMAIL || "partners@nesthelperwa.com",
    jobs: process.env.NEXT_PUBLIC_JOBS_EMAIL || "jobs@nesthelperwa.com",
    admin: process.env.NEXT_PUBLIC_ADMIN_EMAIL || "admin@nesthelperwa.com",
    info: process.env.NEXT_PUBLIC_INFO_EMAIL || "info@nesthelperwa.com",
    contact: process.env.NEXT_PUBLIC_CONTACT_ALIAS_EMAIL || "contact@nesthelperwa.com",
    help: process.env.NEXT_PUBLIC_HELP_EMAIL || "help@nesthelperwa.com",
  },
  phone: "(425) 790-1330",
  phoneHref: "tel:+14257901330",
  serviceArea: "Woodinville, Bothell, Kirkland, Redmond & nearby Eastside communities",
  foundingCode: "FOUNDINGFAMILY",
  assets: {
    logo: "/assets/brand/nesthelper-logo.png",
    icon: "/assets/brand/nesthelper-icon.png",
    hero: "/assets/brand/nesthelper-hero-banner.png",
    badge: "/assets/brand/gold-star-checked-badge.png",
    og: "/assets/social/og-nesthelper.png"
  }
};
